CREATE TABLE UTENTE(
MATRICOLA INTEGER NOT NULL,
NUMERO_TEL INTEGER NOT NULL,
CAP INTEGER NOT NULL,
NUMERO INTEGER NOT NULL,
VIA VARCHAR(16) NOT NULL,
CITTA VARCHAR(15) NOT NULL,
COGNOME VARCHAR(12) NOT NULL,
NOME VARCHAR(12) NOT NULL,
PRIMARY KEY (MATRICOLA),
UNIQUE (MATRICOLA)
);


CREATE TABLE SUCCURSALE(
COD_SUC INTEGER NOT NULL,
DIPARTIMENTO VARCHAR(15) NOT NULL,
VIA VARCHAR(16) NOT NULL,
NUMERO INTEGER NOT NULL,
CAP INTEGER NOT NULL,
CITTA VARCHAR(15) NOT NULL,
PRIMARY KEY (COD_SUC),
UNIQUE (COD_SUC)
);

CREATE TABLE LIBRO(
COD_LIBRO INTEGER NOT NULL,
ISBN VARCHAR(12) NOT NULL,
TITOLO VARCHAR(16) NOT NULL,
ANNO_PUB DATE NOT NULL,
LINGUA VARCHAR(10) NOT NULL,
COD_SUC INTEGER NOT NULL,
PRIMARY KEY (COD_LIBRO),
UNIQUE (COD_LIBRO),
FOREIGN KEY (COD_SUC) REFERENCES SUCCURSALE(COD_SUC)
);

CREATE TABLE PRESTITO(
COD_PRESTITO INTEGER NOT NULL,
DATA_PRESTITO DATE NOT NULL,
MATRICOLA INTEGER NOT NULL,
COD_LIBRO INTEGER NOT NULL,
PRIMARY KEY (COD_PRESTITO),
UNIQUE (COD_PRESTITO),
FOREIGN KEY (MATRICOLA) REFERENCES UTENTE(MATRICOLA),
FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO)
);

CREATE TABLE AUTORE(
COD_AUTORE INTEGER NOT NULL,
NOME VARCHAR(16) NOT NULL,
COGNOME VARCHAR(16) NOT NULL,
DATA_NASCITA DATE NOT NULL,
LUOGO_NASCITA VARCHAR(16) NOT NULL,
PRIMARY KEY (COD_AUTORE),
UNIQUE (COD_AUTORE)
);

CREATE TABLE BOOK_AUTHORS(
COD_BOOK_AUTHORS INTEGER NOT NULL,
COD_LIBRO INTEGER NOT NULL,
COD_AUTORE INTEGER NOT NULL,
PRIMARY KEY (COD_BOOK_AUTHORS),
UNIQUE (COD_BOOK_AUTHORS),
FOREIGN KEY (COD_LIBRO) REFERENCES LIBRO(COD_LIBRO),
FOREIGN KEY (COD_AUTORE) REFERENCES AUTORE(COD_AUTORE)
);