USE BIBLIOTECA;
SELECT LIBRO.COD_LIBRO, TITOLO
FROM (LIBRO
INNER JOIN BOOK_AUTHORS ON BOOK_AUTHORS.COD_LIBRO = LIBRO.COD_LIBRO)
WHERE COD_AUTORE=1
ORDER BY ANNO_PUB;

SELECT PRESTITO.COD_LIBRO, DATA_PRESTITO,TITOLO,ISBN,LINGUA,ANNO_PUB
FROM (PRESTITO 
INNER JOIN LIBRO ON PRESTITO.COD_LIBRO = LIBRO.COD_LIBRO) 
WHERE MATRICOLA=1;

SELECT COD_PRESTITO, DATA_PRESTITO, PRESTITO.COD_LIBRO, PRESTITO.MATRICOLA, NOME, COGNOME, TITOLO 
FROM ((PRESTITO
INNER JOIN UTENTE ON PRESTITO.MATRICOLA=UTENTE.MATRICOLA)
INNER JOIN LIBRO ON PRESTITO.COD_LIBRO = LIBRO.COD_LIBRO);

SELECT * 
FROM AUTORE
WHERE COD_AUTORE LIKE '%1%'
OR NOME LIKE '%A%'
OR COGNOME LIKE '%A%'
OR DATA_NASCITA LIKE '%%'
OR LUOGO_NASCITA LIKE '%A%';

SELECT COUNT(*) 
FROM LIBRO
WHERE ANNO_PUB LIKE '%1%';

SELECT COUNT(*)
FROM (PRESTITO
INNER JOIN LIBRO 
ON LIBRO.COD_LIBRO= PRESTITO.COD_LIBRO)
WHERE COD_SUC LIKE '%1%';


SELECT COUNT(*), NOME
FROM ((LIBRO INNER JOIN BOOK_AUTHORS 
ON BOOK_AUTHORS.COD_LIBRO=LIBRO.COD_LIBRO)
INNER JOIN AUTORE
ON AUTORE.COD_AUTORE=BOOK_AUTHORS.COD_AUTORE)
GROUP BY NOME;

SELECT *
FROM PRESTITO
WHERE DATA_PRESTITO BETWEEN '2023-01-11' AND '2023-01-12';
