USE BIBLIOTECA;
SELECT LIBRO.COD_LIBRO, TITOLO
FROM (LIBRO
INNER JOIN BOOK_AUTHORS ON BOOK_AUTHORS.COD_LIBRO = LIBRO.COD_LIBRO)
WHERE COD_AUTORE=1
ORDER BY ANNO_PUB;

SELECT PRESTITO.COD_LIBRO, DATA_PRESTITO,TITOLO,ISBN,LINGUA,ANNO_PUB
FROM (PRESTITO 
INNER JOIN LIBRO ON PRESTITO.COD_LIBRO = LIBRO.COD_LIBRO) 
WHERE MATRICOLA=1;

SELECT COD_PRESTITO, DATA_PRESTITO, PRESTITO.COD_LIBRO, PRESTITO.MATRICOLA, NOME, COGNOME, TITOLO 
FROM ((PRESTITO
INNER JOIN UTENTE ON PRESTITO.MATRICOLA=UTENTE.MATRICOLA)
INNER JOIN LIBRO ON PRESTITO.COD_LIBRO = LIBRO.COD_LIBRO);

SELECT * 
FROM AUTORE
WHERE COD_AUTORE LIKE '%1%'
OR NOME LIKE '%A%'
OR COGNOME LIKE '%A%'
OR DATA_NASCITA LIKE '%%'
OR LUOGO_NASCITA LIKE '%A%';

SELECT COUNT(*) 
FROM LIBRO
WHERE ANNO_PUB LIKE '%1%';

SELECT COUNT(*)
FROM (PRESTITO
INNER JOIN LIBRO 
ON LIBRO.COD_LIBRO= PRESTITO.COD_LIBRO)
WHERE COD_SUC LIKE '%1%';


SELECT COUNT(*), NOME
FROM ((LIBRO INNER JOIN BOOK_AUTHORS 
ON BOOK_AUTHORS.COD_LIBRO=LIBRO.COD_LIBRO)
INNER JOIN AUTORE
ON AUTORE.COD_AUTORE=BOOK_AUTHORS.COD_AUTORE)
GROUP BY NOME;

SELECT *
FROM PRESTITO
WHERE DATA_PRESTITO BETWEEN '2023-01-11' AND '2023-01-12';

#VISUALIZZAZIONE DEGLI AUTORI CHE HANNO UN PRESTITO CON UNA DETERMINATA LINGUA 
SELECT UTENTE.NOME,UTENTE.COGNOME,TITOLO,LINGUA,AUTORE.NOME
FROM ((((UTENTE 
INNER JOIN PRESTITO
ON UTENTE.MATRICOLA=PRESTITO.MATRICOLA)
INNER JOIN LIBRO 
ON LIBRO.COD_LIBRO=PRESTITO.COD_LIBRO)
INNER JOIN BOOK_AUTHORS
ON BOOK_AUTHORS.COD_LIBRO=LIBRO.COD_LIBRO)
INNER JOIN AUTORE
ON BOOK_AUTHORS.COD_AUTORE=AUTORE.COD_AUTORE)
WHERE LINGUA='English';

#conteggio autori con una determinata lingua
SELECT COUNT(AUTORE.COD_AUTORE)
FROM ((((UTENTE 
INNER JOIN PRESTITO
ON UTENTE.MATRICOLA=PRESTITO.MATRICOLA)
INNER JOIN LIBRO 
ON LIBRO.COD_LIBRO=PRESTITO.COD_LIBRO)
INNER JOIN BOOK_AUTHORS
ON BOOK_AUTHORS.COD_LIBRO=LIBRO.COD_LIBRO)
INNER JOIN AUTORE
ON BOOK_AUTHORS.COD_AUTORE=AUTORE.COD_AUTORE)
WHERE LINGUA='English';

#CONTEGGIO LIBRI CON QUELLA LINGUA DI QUELL'AUTORE PRESI IN PRESTITO
SELECT COUNT(LIBRO.COD_LIBRO),AUTORE.NOME
FROM (((PRESTITO
INNER JOIN LIBRO 
ON LIBRO.COD_LIBRO=PRESTITO.COD_LIBRO)
INNER JOIN BOOK_AUTHORS
ON BOOK_AUTHORS.COD_LIBRO=LIBRO.COD_LIBRO)
INNER JOIN AUTORE
ON BOOK_AUTHORS.COD_AUTORE=AUTORE.COD_AUTORE)
WHERE LINGUA='English'
GROUP BY AUTORE.COD_AUTORE;

SELECT * 
FROM PRESTITO
WHERE DATA_PRESTITO<'2023-01-24';

#CONTEGGIO LIBRI CON QUELLA LINGUA DI QUELL'AUTORE
SELECT COUNT(LIBRO.COD_LIBRO),AUTORE.NOME
FROM ((LIBRO 
INNER JOIN BOOK_AUTHORS
ON BOOK_AUTHORS.COD_LIBRO=LIBRO.COD_LIBRO)
INNER JOIN AUTORE
ON BOOK_AUTHORS.COD_AUTORE=AUTORE.COD_AUTORE)
WHERE LINGUA='English'
GROUP BY AUTORE.COD_AUTORE;

#LA SUCCURSALE PREFERITA DA OGNI UTENTE CHE HA PRESO IN PRESTITO UN LIBRO
SELECT UTENTE.NOME, UTENTE.COGNOME, MAX(CONTEGGIO)
FROM(
SELECT COUNT(SUCCURSALE.DIPARTIMENTO)
FROM (((UTENTE 
INNER JOIN PRESTITO
ON UTENTE.MATRICOLA=PRESTITO.MATRICOLA)
INNER JOIN LIBRO 
ON LIBRO.COD_LIBRO=PRESTITO.COD_LIBRO)
INNER JOIN SUCCURSALE
ON LIBRO.COD_SUC=SUCCURSALE.COD_SUC)
GROUP BY UTENTE.MATRICOLA, SUCCURSALE.DIPARTIMENTO) AS CONTEGGIO;

SELECT UTENTE.MATRICOLA, UTENTE.NOME, UTENTE.COGNOME, MAX(CONTEGGIO) AS MaxConteggio, SUCCURSALE.DIPARTIMENTO
FROM (((
    SELECT UTENTE.MATRICOLA, COUNT(SUCCURSALE.DIPARTIMENTO) AS CONTEGGIO, SUCCURSALE.DIPARTIMENTO
    FROM (((UTENTE 
    INNER JOIN PRESTITO ON UTENTE.MATRICOLA=PRESTITO.MATRICOLA)
    INNER JOIN LIBRO ON LIBRO.COD_LIBRO=PRESTITO.COD_LIBRO)
    INNER JOIN SUCCURSALE ON LIBRO.COD_SUC=SUCCURSALE.COD_SUC)
    GROUP BY UTENTE.MATRICOLA, SUCCURSALE.DIPARTIMENTO
) AS CONTEGGI_UTENTE
INNER JOIN UTENTE ON UTENTE.MATRICOLA = CONTEGGI_UTENTE.MATRICOLA)
INNER JOIN SUCCURSALE ON SUCCURSALE.DIPARTIMENTO = CONTEGGI_UTENTE.DIPARTIMENTO)
GROUP BY UTENTE.MATRICOLA;
#GIUSTA NON
SELECT UTENTE.MATRICOLA, UTENTE.NOME, UTENTE.COGNOME, MAX(CONTEGGIO) AS MaxConteggio, SUCCURSALE.DIPARTIMENTO
FROM (
    SELECT UTENTE.MATRICOLA,UTENTE.NOME,UTENTE.COGNOME, COUNT(SUCCURSALE.DIPARTIMENTO) AS CONTEGGIO, SUCCURSALE.DIPARTIMENTO
    FROM (((UTENTE 
    INNER JOIN PRESTITO ON UTENTE.MATRICOLA=PRESTITO.MATRICOLA)
    INNER JOIN LIBRO ON LIBRO.COD_LIBRO=PRESTITO.COD_LIBRO)
    INNER JOIN SUCCURSALE ON LIBRO.COD_SUC=SUCCURSALE.COD_SUC)
    GROUP BY UTENTE.MATRICOLA, SUCCURSALE.DIPARTIMENTO
) AS CONTEGGI_UTENTE
INNER JOIN UTENTE ON UTENTE.MATRICOLA = CONTEGGI_UTENTE.MATRICOLA
INNER JOIN SUCCURSALE ON SUCCURSALE.DIPARTIMENTO = CONTEGGI_UTENTE.DIPARTIMENTO
GROUP BY UTENTE.MATRICOLA, SUCCURSALE.DIPARTIMENTO
ORDER BY UTENTE.MATRICOLA;

#FINALE ma no
SELECT UTENTE.MATRICOLA, CONTEGGIO.DIPARTIMENTO, CONTEGGIO.CONTEGGIO, UTENTE.NOME, UTENTE.COGNOME
FROM UTENTE
 JOIN (
    SELECT PRESTITO.MATRICOLA, SUCCURSALE.DIPARTIMENTO, COUNT(*) AS CONTEGGIO
    FROM PRESTITO
    JOIN LIBRO ON LIBRO.COD_LIBRO = PRESTITO.COD_LIBRO
    JOIN SUCCURSALE ON LIBRO.COD_SUC = SUCCURSALE.COD_SUC
    GROUP BY PRESTITO.MATRICOLA, SUCCURSALE.DIPARTIMENTO
) AS CONTEGGIO ON CONTEGGIO.MATRICOLA = UTENTE.MATRICOLA;



SELECT UTENTE.NOME, UTENTE.COGNOME, MAX(CONTEGGIO) AS MaxConteggio, DIP
FROM (
    SELECT UTENTE.MATRICOLA, COUNT(SUCCURSALE.DIPARTIMENTO) AS CONTEGGIO, SUCCURSALE.DIPARTIMENTO AS DIP
    FROM (((UTENTE 
    INNER JOIN PRESTITO ON UTENTE.MATRICOLA=PRESTITO.MATRICOLA)
    INNER JOIN LIBRO ON LIBRO.COD_LIBRO=PRESTITO.COD_LIBRO)
    INNER JOIN SUCCURSALE ON LIBRO.COD_SUC=SUCCURSALE.COD_SUC)
    GROUP BY UTENTE.MATRICOLA, SUCCURSALE.COD_SUC
) AS CONTEGGI_UTENTE
INNER JOIN UTENTE ON UTENTE.MATRICOLA = CONTEGGI_UTENTE.MATRICOLA
GROUP BY UTENTE.MATRICOLA;

#parzialmente giusta
SELECT UTENTE.NOME, UTENTE.COGNOME, MAX(CONTEGGIO) AS MaxConteggio
    FROM (
        SELECT UTENTE.MATRICOLA, COUNT(SUCCURSALE.DIPARTIMENTO) AS CONTEGGIO
        FROM (((UTENTE 
        INNER JOIN PRESTITO ON UTENTE.MATRICOLA=PRESTITO.MATRICOLA)
        INNER JOIN LIBRO ON LIBRO.COD_LIBRO=PRESTITO.COD_LIBRO)
        INNER JOIN SUCCURSALE ON LIBRO.COD_SUC=SUCCURSALE.COD_SUC)
        GROUP BY UTENTE.MATRICOLA, SUCCURSALE.COD_SUC
     ) AS CONTEGGI_UTENTE
	 INNER JOIN UTENTE ON UTENTE.MATRICOLA = CONTEGGI_UTENTE.MATRICOLA
	 GROUP BY UTENTE.MATRICOLA;